FROM node:20-alpine AS build
WORKDIR /app

COPY src/frontend-angular/book-admin/package*.json ./src/frontend-angular/book-admin/
WORKDIR /app/src/frontend-angular/book-admin
RUN npm ci

WORKDIR /app
COPY src/frontend-angular/book-admin ./src/frontend-angular/book-admin
COPY src/shared ./src/shared

WORKDIR /app/src/frontend-angular/book-admin
RUN npm run build

FROM nginx:1.27-alpine AS runtime
COPY docker/nginx.angular.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/src/frontend-angular/book-admin/dist/book-admin/browser /usr/share/nginx/html

EXPOSE 80
